### ISSUE TITLE
Awesome tool! It's not working as described though...

### ISSUE THREAD

**Issue by rjcorwin** [millermedeiros/gh-markdown-cli#9]
Hi there. Thanks for writing this awesome script, it's really handy for my writing workflow.  Unfortunately it does not work as described in the documentation.  I'm on a Mac and if I do...

`
   mdown -i Video-Book-Manual/README.md -o output/new.html
`

The Video-Book-Manual/README.md file is overwritten with its HTML equivalent while there is nothing put in the output directory.

If I do...

`
   mdown -i Video-Book-Manual -o output
`

Then I get an error...

`
fs.js:381
  var r = binding.read(fd, buffer, offset, length, position);
                  ^
Error: EISDIR, illegal operation on a directory
    at Object.fs.readSync (fs.js:381:19)
    at Object.fs.readFileSync (fs.js:208:28)
    at exports.batchProcess (/usr/local/lib/node_modules/gh-markdown-cli/mdown.js:24:46)
    at Array.forEach (native)
    at exports.batchProcess (/usr/local/lib/node_modules/gh-markdown-cli/mdown.js:23:15)
    at Glob.<anonymous> (/usr/local/lib/node_modules/gh-markdown-cli/node_modules/glob/glob.js:90:7)
    at Glob.EventEmitter.emit (events.js:96:17)
    at Glob._processEmitQueue (/usr/local/lib/node_modules/gh-markdown-cli/node_modules/glob/glob.js:280:10)
    at Glob.emitMatch (/usr/local/lib/node_modules/gh-markdown-cli/node_modules/glob/glob.js:265:8)
    at Glob._finish (/usr/local/lib/node_modules/gh-markdown-cli/node_modules/glob/glob.js:227:8)
`

The only way I can currently use this tool is if I do...

`
mdown -i Video-Book-Manual/README.md > output/README.html
`

That works as one might expect with the HTML equivalent of Video-Book-Manual/README.md being saved to output/README.html.

**Comment by rehia** [comment]
The error is because of the lack of filename in the input.
It doesn't support a directory as input
